FROM python:3.6

WORKDIR /var/oasis

RUN mkdir -p /var/log/oasis

RUN apt-get update && apt-get install -y --no-install-recommends unixodbc-dev libspatialindex-dev tree && rm -rf /var/lib/apt/lists/*

# Copy startup script + server config
COPY ./testscript/api/ ./
RUN chmod +x ./api_integration.py

ENTRYPOINT ["/bin/bash", "-c", "python run_model.py \"$@\"", "--"]
