FROM python:3.8

WORKDIR /var/oasis

RUN mkdir -p /var/log/oasis
RUN apt-get update && \
    apt-get install -y --no-install-recommends unixodbc-dev libspatialindex-dev tree && \
    apt-get install -y python3-pip && \
    rm -rf /var/lib/apt/lists/*
RUN pip install subprocess32

COPY ./testscript/run_model.py ./
RUN chmod +x ./run_model.py

ENTRYPOINT ["/bin/bash", "-c", "python run_model.py \"$@\"", "--"]
