version: '3'
services:
  worker:
    image: ${IMAGE_WORKER}:${TAG_RUN_WORKER}
    links:
     - celery-db
     - rabbit:myrabbit
    environment:
     - OASIS_MODEL_SUPPLIER_ID=${MODEL_SUPPLIER}
     - OASIS_MODEL_ID=${MODEL_VARIENT}
     - OASIS_MODEL_VERSION_ID=${MODEL_ID}
     - OASIS_MODEL_DATA_DIRECTORY=/var/oasis/  
     - OASIS_RABBIT_HOST=rabbit
     - OASIS_RABBIT_PORT=5672
     - OASIS_RABBIT_USER=rabbit
     - OASIS_RABBIT_PASS=rabbit
     - OASIS_CELERY_DB_ENGINE=db+mysql+pymysql
     - OASIS_CELERY_DB_HOST=celery-db
     - OASIS_CELERY_DB_PASS=password
     - OASIS_CELERY_DB_USER=celery
     - OASIS_CELERY_DB_NAME=celery
     - OASIS_CELERY_DB_PORT=3306
     - OASIS_OASISLMF_CONFIG=${MDK_CONFIG}  
     - OASIS_MODEL_DATA_DIRECTORY=/home/worker/model/  
     - OASIS_KEEP_RUN_DIR=True
     - OASIS_DEBUG_MODE=True
     - OASIS_DEBUG=True
    volumes:
     - ${OASIS_MODEL_REPO_DIR}:${MODEL_MOUNT_TARGET:-/home/worker/model}:rw
     - ${OASIS_MODEL_DATA_DIR}:${MODEL_DATA_TARGET:-/var/oasis/model_data}:rw
     - ${OASIS_MEDIA_ROOT:-./docker-shared-fs}:/shared-fs:rw
