version: '3.0'
services:
  model_tester:
    image: ${IMAGE_WORKER}:${TAG_RUN_WORKER}
    environment:
     - TEST_TIMEOUT=${TEST_MAX_RUNTIME}
    volumes:
     - ${TEST_DATA_DIR}:/var/oasis/test
     - ../stage/output:/var/oasis/test/output:rw
    # - ../stage/input:/var/oasis/test/input:rw
