version: '3'
services:
  server:
   image: coreoasis/api_server:${TAG_RUN_PLATFORM}
   links:
     - server-db
     - celery-db
     - rabbit
   environment:
     - OASIS_ADMIN_USER=admin
     - OASIS_ADMIN_PASS=password 
     - OASIS_DEBUG=1
     - OASIS_RABBIT_HOST=rabbit
     - OASIS_RABBIT_PORT=5672
     - OASIS_RABBIT_USER=rabbit
     - OASIS_RABBIT_PASS=rabbit
     - OASIS_SERVER_DB_HOST=server-db
     - OASIS_SERVER_DB_PASS=oasis
     - OASIS_SERVER_DB_USER=oasis
     - OASIS_SERVER_DB_NAME=oasis
     - OASIS_SERVER_DB_PORT=3306
     - OASIS_CELERY_DB_ENGINE=db+mysql+pymysql
     - OASIS_CELERY_DB_HOST=celery-db
     - OASIS_CELERY_DB_PASS=password
     - OASIS_CELERY_DB_USER=celery
     - OASIS_CELERY_DB_NAME=celery
     - OASIS_CELERY_DB_PORT=3306
     - STARTUP_RUN_MIGRATIONS=true
   volumes:
     - ../stage/log/server:/var/log/oasis:rw
     - ${OASIS_MEDIA_ROOT:-./docker-shared-fs}:/shared-fs:rw
  worker-monitor:
   image: coreoasis/api_server:${TAG_RUN_PLATFORM}
   command: [wait-for-server, 'server:8000', celery, -A, src.server.oasisapi, worker, --loglevel=INFO]
   links:
     - server-db
     - celery-db
     - rabbit
   environment:
     - OASIS_DEBUG=1
     - OASIS_RABBIT_HOST=rabbit
     - OASIS_RABBIT_PORT=5672
     - OASIS_RABBIT_USER=rabbit
     - OASIS_RABBIT_PASS=rabbit
     - OASIS_SERVER_DB_HOST=server-db
     - OASIS_SERVER_DB_PASS=oasis
     - OASIS_SERVER_DB_USER=oasis
     - OASIS_SERVER_DB_NAME=oasis
     - OASIS_SERVER_DB_PORT=3306
     - OASIS_CELERY_DB_ENGINE=db+mysql+pymysql
     - OASIS_CELERY_DB_HOST=celery-db
     - OASIS_CELERY_DB_PASS=password
     - OASIS_CELERY_DB_USER=celery
     - OASIS_CELERY_DB_NAME=celery
     - OASIS_CELERY_DB_PORT=3306
   volumes:
     - ../stage/log/monitor:/var/log/oasis:rw
     - ${OASIS_MEDIA_ROOT:-./docker-shared-fs}:/shared-fs:rw
  server-db:
    image: mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=oasis
      - MYSQL_PASSWORD=oasis
      - MYSQL_DATABASE=oasis
    volumes:
      - ${OASIS_DOCKER_DB_DATA_DIR:-./db-data}/server:/var/lib/mysql/:rw
  celery-db:
    image: mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=celery
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=celery
    volumes:
      - ${OASIS_DOCKER_DB_DATA_DIR:-./db-data}/celery:/var/lib/mysql/:rw
  rabbit:
    image: rabbitmq:3.8.14-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
