
version: '3'
services:
  worker:
    image: ${IMAGE_WORKER}:${TAG_RUN_WORKER}
    links:
     - celery-db
     - rabbit:myrabbit
    environment:
     - OASIS_MODEL_SUPPLIER_ID=${MODEL_SUPPLIER}
     - OASIS_MODEL_ID=${MODEL_VARIENT}
     - OASIS_MODEL_VERSION_ID=${MODEL_ID}
     - OASIS_RABBIT_HOST=rabbit
     - OASIS_RABBIT_PORT=5672
     - OASIS_RABBIT_USER=rabbit
     - OASIS_RABBIT_PASS=rabbit
     - OASIS_CELERY_DB_ENGINE=db+mysql+pymysql
     - OASIS_CELERY_DB_HOST=celery-db
     - OASIS_CELERY_DB_PASS=password
     - OASIS_CELERY_DB_USER=celery
     - OASIS_CELERY_DB_NAME=celery
     - OASIS_CELERY_DB_PORT=3306
     - OASIS_KEEP_RUN_DIR=True
     - OASIS_DEBUG_MODE=True
     - OASIS_STORAGE_TYPE=S3
     - OASIS_AWS_BUCKET_NAME=example-bucket 
     - OASIS_AWS_ACCESS_KEY_ID=foobar
     - OASIS_AWS_SECRET_ACCESS_KEY=foobar  
     - OASIS_AWS_S3_ENDPOINT_URL=http://localstack-s3:4572
    volumes:
#     - ./log:/var/log/oasis:rw
     - ${OASIS_MODEL_DATA_DIR:-./data/static}:${MODEL_MOUNT_TARGET:-/home/worker/model}:rw
